//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mega_test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Автомобиль.
    /// </summary>
    // *** Start programmer edit section *** (Авто CustomAttributes)

    // *** End programmer edit section *** (Авто CustomAttributes)
    [AutoAltered()]
    [Caption("Автомобиль")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АвтоE", new string[] {
            "Номер as \'Номер\'",
            "Водитель as \'Водитель\'",
            "Водитель.Тел as \'Тел\'"}, Hidden=new string[] {
            "Водитель.Тел"})]
    [MasterViewDefineAttribute("АвтоE", "Водитель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Тел")]
    [View("АвтоL", new string[] {
            "Номер as \'Номер\'",
            "Водитель.Тел as \'Тел\'",
            "Водитель as \'Водитель\'"})]
    [View("АвтомобильE", new string[] {
            "Номер as \'Номер\'"})]
    [View("АвтомобильL", new string[] {
            "Номер as \'Номер\'"})]
    public class Авто : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомер;
        
        private IIS.Mega_test.Водитель fВодитель;
        
        // *** Start programmer edit section *** (Авто CustomMembers)

        // *** End programmer edit section *** (Авто CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Авто.Номер CustomAttributes)

        // *** End programmer edit section *** (Авто.Номер CustomAttributes)
        [StrLen(255)]
        public virtual string Номер
        {
            get
            {
                // *** Start programmer edit section *** (Авто.Номер Get start)

                // *** End programmer edit section *** (Авто.Номер Get start)
                string result = this.fНомер;
                // *** Start programmer edit section *** (Авто.Номер Get end)

                // *** End programmer edit section *** (Авто.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Авто.Номер Set start)

                // *** End programmer edit section *** (Авто.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Авто.Номер Set end)

                // *** End programmer edit section *** (Авто.Номер Set end)
            }
        }
        
        /// <summary>
        /// Автомобиль.
        /// </summary>
        // *** Start programmer edit section *** (Авто.Водитель CustomAttributes)

        // *** End programmer edit section *** (Авто.Водитель CustomAttributes)
        [PropertyStorage(new string[] {
                "Водитель"})]
        [NotNull()]
        public virtual IIS.Mega_test.Водитель Водитель
        {
            get
            {
                // *** Start programmer edit section *** (Авто.Водитель Get start)

                // *** End programmer edit section *** (Авто.Водитель Get start)
                IIS.Mega_test.Водитель result = this.fВодитель;
                // *** Start programmer edit section *** (Авто.Водитель Get end)

                // *** End programmer edit section *** (Авто.Водитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Авто.Водитель Set start)

                // *** End programmer edit section *** (Авто.Водитель Set start)
                this.fВодитель = value;
                // *** Start programmer edit section *** (Авто.Водитель Set end)

                // *** End programmer edit section *** (Авто.Водитель Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АвтоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвтоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвтоE", typeof(IIS.Mega_test.Авто));
                }
            }
            
            /// <summary>
            /// "АвтоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвтоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвтоL", typeof(IIS.Mega_test.Авто));
                }
            }
            
            /// <summary>
            /// "АвтомобильE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвтомобильE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвтомобильE", typeof(IIS.Mega_test.Авто));
                }
            }
            
            /// <summary>
            /// "АвтомобильL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвтомобильL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвтомобильL", typeof(IIS.Mega_test.Авто));
                }
            }
        }
    }
}
