//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mega_test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Билет.
    /// </summary>
    // *** Start programmer edit section *** (Билет CustomAttributes)

    // *** End programmer edit section *** (Билет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БилетE", new string[] {
            "ВреПеч as \'Время печати\'",
            "ВреОконч as \'Окончание\'",
            "Ном as \'Номер\'",
            "Водитель as \'Водитель\'",
            "Паркомат as \'Паркомат\'"})]
    [View("БилетL", new string[0])]
    public class Билет : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fВреПеч;
        
        private System.DateTime fВреОконч;
        
        private int fНом;
        
        private IIS.Mega_test.Паркомат fПаркомат;
        
        private IIS.Mega_test.Водитель fВодитель;
        
        // *** Start programmer edit section *** (Билет CustomMembers)

        // *** End programmer edit section *** (Билет CustomMembers)

        
        /// <summary>
        /// ВреОконч.
        /// </summary>
        // *** Start programmer edit section *** (Билет.ВреОконч CustomAttributes)

        // *** End programmer edit section *** (Билет.ВреОконч CustomAttributes)
        public virtual System.DateTime ВреОконч
        {
            get
            {
                // *** Start programmer edit section *** (Билет.ВреОконч Get start)

                // *** End programmer edit section *** (Билет.ВреОконч Get start)
                System.DateTime result = this.fВреОконч;
                // *** Start programmer edit section *** (Билет.ВреОконч Get end)

                // *** End programmer edit section *** (Билет.ВреОконч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билет.ВреОконч Set start)

                // *** End programmer edit section *** (Билет.ВреОконч Set start)
                this.fВреОконч = value;
                // *** Start programmer edit section *** (Билет.ВреОконч Set end)

                // *** End programmer edit section *** (Билет.ВреОконч Set end)
            }
        }
        
        /// <summary>
        /// ВреПеч.
        /// </summary>
        // *** Start programmer edit section *** (Билет.ВреПеч CustomAttributes)

        // *** End programmer edit section *** (Билет.ВреПеч CustomAttributes)
        public virtual System.DateTime ВреПеч
        {
            get
            {
                // *** Start programmer edit section *** (Билет.ВреПеч Get start)

                // *** End programmer edit section *** (Билет.ВреПеч Get start)
                System.DateTime result = this.fВреПеч;
                // *** Start programmer edit section *** (Билет.ВреПеч Get end)

                // *** End programmer edit section *** (Билет.ВреПеч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билет.ВреПеч Set start)

                // *** End programmer edit section *** (Билет.ВреПеч Set start)
                this.fВреПеч = value;
                // *** Start programmer edit section *** (Билет.ВреПеч Set end)

                // *** End programmer edit section *** (Билет.ВреПеч Set end)
            }
        }
        
        /// <summary>
        /// Ном.
        /// </summary>
        // *** Start programmer edit section *** (Билет.Ном CustomAttributes)

        // *** End programmer edit section *** (Билет.Ном CustomAttributes)
        public virtual int Ном
        {
            get
            {
                // *** Start programmer edit section *** (Билет.Ном Get start)

                // *** End programmer edit section *** (Билет.Ном Get start)
                int result = this.fНом;
                // *** Start programmer edit section *** (Билет.Ном Get end)

                // *** End programmer edit section *** (Билет.Ном Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билет.Ном Set start)

                // *** End programmer edit section *** (Билет.Ном Set start)
                this.fНом = value;
                // *** Start programmer edit section *** (Билет.Ном Set end)

                // *** End programmer edit section *** (Билет.Ном Set end)
            }
        }
        
        /// <summary>
        /// Билет.
        /// </summary>
        // *** Start programmer edit section *** (Билет.Водитель CustomAttributes)

        // *** End programmer edit section *** (Билет.Водитель CustomAttributes)
        [PropertyStorage(new string[] {
                "Водитель"})]
        [NotNull()]
        public virtual IIS.Mega_test.Водитель Водитель
        {
            get
            {
                // *** Start programmer edit section *** (Билет.Водитель Get start)

                // *** End programmer edit section *** (Билет.Водитель Get start)
                IIS.Mega_test.Водитель result = this.fВодитель;
                // *** Start programmer edit section *** (Билет.Водитель Get end)

                // *** End programmer edit section *** (Билет.Водитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билет.Водитель Set start)

                // *** End programmer edit section *** (Билет.Водитель Set start)
                this.fВодитель = value;
                // *** Start programmer edit section *** (Билет.Водитель Set end)

                // *** End programmer edit section *** (Билет.Водитель Set end)
            }
        }
        
        /// <summary>
        /// Билет.
        /// </summary>
        // *** Start programmer edit section *** (Билет.Паркомат CustomAttributes)

        // *** End programmer edit section *** (Билет.Паркомат CustomAttributes)
        [PropertyStorage(new string[] {
                "Паркомат"})]
        [NotNull()]
        public virtual IIS.Mega_test.Паркомат Паркомат
        {
            get
            {
                // *** Start programmer edit section *** (Билет.Паркомат Get start)

                // *** End programmer edit section *** (Билет.Паркомат Get start)
                IIS.Mega_test.Паркомат result = this.fПаркомат;
                // *** Start programmer edit section *** (Билет.Паркомат Get end)

                // *** End programmer edit section *** (Билет.Паркомат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билет.Паркомат Set start)

                // *** End programmer edit section *** (Билет.Паркомат Set start)
                this.fПаркомат = value;
                // *** Start programmer edit section *** (Билет.Паркомат Set end)

                // *** End programmer edit section *** (Билет.Паркомат Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БилетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БилетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БилетE", typeof(IIS.Mega_test.Билет));
                }
            }
            
            /// <summary>
            /// "БилетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БилетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БилетL", typeof(IIS.Mega_test.Билет));
                }
            }
        }
    }
}
