//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mega_test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Водитель.
    /// </summary>
    // *** Start programmer edit section *** (Водитель CustomAttributes)

    // *** End programmer edit section *** (Водитель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВодительE", new string[] {
            "Карта as \'Номер карты\'",
            "Тел as \'Номер телефона\'"})]
    [View("ВодительL", new string[0])]
    public class Водитель : ICSSoft.STORMNET.DataObject
    {
        
        private string fТел;
        
        private string fКарта;
        
        // *** Start programmer edit section *** (Водитель CustomMembers)

        // *** End programmer edit section *** (Водитель CustomMembers)

        
        /// <summary>
        /// Карта.
        /// </summary>
        // *** Start programmer edit section *** (Водитель.Карта CustomAttributes)

        // *** End programmer edit section *** (Водитель.Карта CustomAttributes)
        [StrLen(255)]
        public virtual string Карта
        {
            get
            {
                // *** Start programmer edit section *** (Водитель.Карта Get start)

                // *** End programmer edit section *** (Водитель.Карта Get start)
                string result = this.fКарта;
                // *** Start programmer edit section *** (Водитель.Карта Get end)

                // *** End programmer edit section *** (Водитель.Карта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Водитель.Карта Set start)

                // *** End programmer edit section *** (Водитель.Карта Set start)
                this.fКарта = value;
                // *** Start programmer edit section *** (Водитель.Карта Set end)

                // *** End programmer edit section *** (Водитель.Карта Set end)
            }
        }
        
        /// <summary>
        /// Тел.
        /// </summary>
        // *** Start programmer edit section *** (Водитель.Тел CustomAttributes)

        // *** End programmer edit section *** (Водитель.Тел CustomAttributes)
        [StrLen(255)]
        public virtual string Тел
        {
            get
            {
                // *** Start programmer edit section *** (Водитель.Тел Get start)

                // *** End programmer edit section *** (Водитель.Тел Get start)
                string result = this.fТел;
                // *** Start programmer edit section *** (Водитель.Тел Get end)

                // *** End programmer edit section *** (Водитель.Тел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Водитель.Тел Set start)

                // *** End programmer edit section *** (Водитель.Тел Set start)
                this.fТел = value;
                // *** Start programmer edit section *** (Водитель.Тел Set end)

                // *** End programmer edit section *** (Водитель.Тел Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВодительE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВодительE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВодительE", typeof(IIS.Mega_test.Водитель));
                }
            }
            
            /// <summary>
            /// "ВодительL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВодительL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВодительL", typeof(IIS.Mega_test.Водитель));
                }
            }
        }
    }
}
