//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mega_test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Кардридер.
    /// </summary>
    // *** Start programmer edit section *** (Кардр CustomAttributes)

    // *** End programmer edit section *** (Кардр CustomAttributes)
    [AutoAltered()]
    [Caption("Кардридер")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КардрE", new string[] {
            "ID as \'ID\'",
            "Паркомат as \'Паркомат\'",
            "Паркомат.СтатОпл as \'Стат опл\'"}, Hidden=new string[] {
            "Паркомат.СтатОпл"})]
    [MasterViewDefineAttribute("КардрE", "Паркомат", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "СтатОпл")]
    [View("КардрL", new string[] {
            "ID as \'ID\'",
            "Паркомат.СтатОпл as \'Стат опл\'"})]
    [View("КардридерE", new string[] {
            "ID as \'ID\'"})]
    [View("КардридерL", new string[] {
            "ID as \'ID\'"})]
    public class Кардр : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private IIS.Mega_test.Паркомат fПаркомат;
        
        // *** Start programmer edit section *** (Кардр CustomMembers)

        // *** End programmer edit section *** (Кардр CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Кардр.ID CustomAttributes)

        // *** End programmer edit section *** (Кардр.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Кардр.ID Get start)

                // *** End programmer edit section *** (Кардр.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Кардр.ID Get end)

                // *** End programmer edit section *** (Кардр.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кардр.ID Set start)

                // *** End programmer edit section *** (Кардр.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Кардр.ID Set end)

                // *** End programmer edit section *** (Кардр.ID Set end)
            }
        }
        
        /// <summary>
        /// Кардридер.
        /// </summary>
        // *** Start programmer edit section *** (Кардр.Паркомат CustomAttributes)

        // *** End programmer edit section *** (Кардр.Паркомат CustomAttributes)
        [PropertyStorage(new string[] {
                "Паркомат"})]
        [NotNull()]
        public virtual IIS.Mega_test.Паркомат Паркомат
        {
            get
            {
                // *** Start programmer edit section *** (Кардр.Паркомат Get start)

                // *** End programmer edit section *** (Кардр.Паркомат Get start)
                IIS.Mega_test.Паркомат result = this.fПаркомат;
                // *** Start programmer edit section *** (Кардр.Паркомат Get end)

                // *** End programmer edit section *** (Кардр.Паркомат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кардр.Паркомат Set start)

                // *** End programmer edit section *** (Кардр.Паркомат Set start)
                this.fПаркомат = value;
                // *** Start programmer edit section *** (Кардр.Паркомат Set end)

                // *** End programmer edit section *** (Кардр.Паркомат Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КардрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КардрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КардрE", typeof(IIS.Mega_test.Кардр));
                }
            }
            
            /// <summary>
            /// "КардрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КардрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КардрL", typeof(IIS.Mega_test.Кардр));
                }
            }
            
            /// <summary>
            /// "КардридерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КардридерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КардридерE", typeof(IIS.Mega_test.Кардр));
                }
            }
            
            /// <summary>
            /// "КардридерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КардридерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КардридерL", typeof(IIS.Mega_test.Кардр));
                }
            }
        }
    }
}
