




CREATE TABLE Кардр (
 primaryKey UUID NOT NULL,
 ID INT NULL,
 Паркомат UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Водитель (
 primaryKey UUID NOT NULL,
 Тел VARCHAR(255) NULL,
 Карта VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Авто (
 primaryKey UUID NOT NULL,
 Номер VARCHAR(255) NULL,
 Водитель UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Билет (
 primaryKey UUID NOT NULL,
 ВреПеч TIMESTAMP(3) NULL,
 ВреОконч TIMESTAMP(3) NULL,
 Ном INT NULL,
 Паркомат UUID NOT NULL,
 Водитель UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Паркомат (
 primaryKey UUID NOT NULL,
 ID2 INT NULL,
 СвМеста INT NULL,
 ВреОпл TIMESTAMP(3) NULL,
 СтатОпл VARCHAR(255) NULL,
 СтоимПарк INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE Кардр ADD CONSTRAINT FKed98338455dacd6ee3d3f7d12cb67956af8a4deb FOREIGN KEY (Паркомат) REFERENCES Паркомат; 
CREATE INDEX Indexed98338455dacd6ee3d3f7d12cb67956af8a4deb on Кардр (Паркомат); 

 ALTER TABLE Авто ADD CONSTRAINT FK421727371549ee28167d993087db2ede7f29caa6 FOREIGN KEY (Водитель) REFERENCES Водитель; 
CREATE INDEX Index421727371549ee28167d993087db2ede7f29caa6 on Авто (Водитель); 

 ALTER TABLE Билет ADD CONSTRAINT FK9ac772e531e850b7a0f88e04ef91b8eb4818b146 FOREIGN KEY (Паркомат) REFERENCES Паркомат; 
CREATE INDEX Index9ac772e531e850b7a0f88e04ef91b8eb4818b146 on Билет (Паркомат); 

 ALTER TABLE Билет ADD CONSTRAINT FK040a459cf83f8809a02f577b50b8f7602db57f5f FOREIGN KEY (Водитель) REFERENCES Водитель; 
CREATE INDEX Index040a459cf83f8809a02f577b50b8f7602db57f5f on Билет (Водитель); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

